service: headlessBrowser

provider:
  name: aws
  runtime: nodejs6.10
  stage: live
  region: eu-west-1
  environment:
    CHROME_PATH: ./headless-chrome/headless_shell

custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack

functions:
  run:
    description: Run headless Chromium
    memorySize: 1536
    timeout: 30
    handler: handler.run
